### ISSUE TITLE
Create my own mapping

### ISSUE THREAD

**Issue by Linuus** [cub-uanic/tmk_keyboard#16]
Hi!

I want to create my own mapping for the ergodox, of course. What is the best way to do that? At first I just edited keymap.c to my liking. But I guess that is a bad idea since I will get merge conlficts later on when I pull in changes from upstream.

So, I made my own `keymap_linus.h` file. I also edited `Makefile.lufa` and added this at the end:
```
linus: OPT_DEFS += -DKEYMAP_LINUS
linus: all
```
And also I had to include the file in keymap.c.

Is this the recommended way to do it?

**Comment by BlindLemonLipschitz** [comment]
I forked Cub's and did pretty much what you're suggesting. [Its](https://github.com/BlindLemonLipschitz/tmk_keyboard/tree/blind_layout/keyboard/ergodox) been working fine for me.

**Comment by olivierpons** [comment]
Hi,

I'm french and I've made a tutorial on this on my French blog.
Anyway, to make it short (I dont know if it's mandatory but it's the way I made it work):
- install cygwin with basic installation
- download the sources from github (here).
- edit Makefile.lua and add the name of your own mapping (in my case it's French mapping thus 'azerty'... so I've added: 

    `azerty: OPT_DEFS += -DKEYMAP_AZERTY`
    `azerty: all`

)

- copy the `keymap_cub.h` into `keymap_azerty.h`
- modify the file to your needs
- download the teen loader command line, so you never have you use your mouse and it's faster: `teensy_loader_cli.exe`
- and compile. I did successfully compile with this command line:

`make -f Makefile.lufa azerty && echo 'Reset your Ergodox please...' && ../../../teensy_loader_cli.exe -mmcu=atmega32u4 -w "ergodox_lufa.hex" && echo 'Test your Ergodox!'`

If you want I'd be glad to send you my azerty layout because I did a huge work on re-working macros so that it's very easy to "locate" the key you want to modify (I just dont know how to "merge" it with the current branch).

You can see in the last picture of my article (click on it) how I've modified the macros, and if you find it easier: http://www.olivierpons.fr/ergodox/ergodox-ma-configuration-clavier/ .

If you want the source code to modify azerty to your need click here and just take the `keymap_azerty.h` file: http://www.olivierpons.fr/ergodox/8-ergodox-source-clavier-azerty/

Enjoy!

**Comment by arvids** [comment]
Hello Olivier,
I have been trying to get the Ergodox and swedish qwerty to play along nicely and this looks like something that can get me in the right direction, thank you!

I think you missed a step in your guide, it seems that you also have to edit the keymap.c file in two places to include the newly created keymap.

**Comment by olivierpons** [comment]
Oh yeah you're right, I forgot this: add those lines:

    #elif defined(KEYMAP_AZERTY)
    #include "keymap_azerty.h"
    #else

in lines 88-91 (or around) to make it work, thank you for your suggestion, I'll modify my blog when I have the time!

**Comment by squarefrog** [comment]
I am going to close this as it doesn't seem like an issue. Feel free to open another if you need help.
